#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run 'sh' with that shell as the first argument, like:
#           sh myscript.sh
#
#       Or if you don't have a POSIX-compliant shell, you can instead run a
#       POSIX-compliant shell interpreter directly, like:
#           bash myscript.sh
#
#   (2) This script uses some features that are unique to POSIX, and therefore
#       will not work in non-POSIX compliant shells (like cmd.exe, PowerShell).
#       If you are getting errors, please run using a POSIX shell.
#
#   (3) This script uses the "uname" command, which might not work on some
#       non-POSIX systems.
#       If you are on a non-POSIX system that lacks a POSIX shell, you will
#       need to run this script with a POSIX shell interpreter instead.
#
#   (4) This script is designed to be run as a script file, NOT sourced.
#
#   (5) The script should exit with code 0 on success, or the specific error
#       code that caused the failure.
#
#   (6) The script respects the JAVA_OPTS, GRADLE_OPTS, and JAVA_TOOL_OPTIONS
#       environment variables for passing JVM arguments.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
# Discard cd standard output in case $CDPATH is set (https://github.com/gradle/gradle/issues/25036)
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar


# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - slashes, backslashes, and quotes, we have to be careful.
    #
    # For Cygwin, we need to convert paths to Windows format for the Java executable and the
    # classpath. For Msys, we need to convert paths to Windows format for the classpath only.
    # The JAVACMD executable and the rest of the arguments are passed as is to the Java launcher.
    #
    # We need to handle the case where we are passed a path that contains backslashes and
    # converts them to forward slashes. For the classpath, if there are paths that contain
    # forward slashes, they will be treated as file:// URIs, so we convert them to Windows
    # paths with backslashes. This is needed because the Java launcher will not handle
    # file:// URIs that contain forward slashes, only backward slashes.
    #
    # The result is that we convert paths for the classpath to backslashes, but keep forward
    # slashes for the JAVACMD path, retaining any quotes.
    for arg do
        if [ -n "${arg}" ] ; then
            # We cannot pass arguments with spaces through cygpath, so we need to handle
            # them carefully. If the argument contains no spaces, we can pass it as is.
            # If it contains spaces, we need to quote it.
            case $arg in
                *\ * )
                    # If the argument contains spaces, we need to quote it when
                    # passing it to cygpath, so we need to add another layer of
                    # quotes around it. We do this by replacing every double quote
                    # in the argument with a backslash-escaped double quote, and
                    # then wrapping the entire argument in double quotes.
                    arg="$( printf '%s' "$arg" | sed 's/"/\\"/g' )"
                    arg="\"$arg\""
                    ;;
            esac
            # Now we can pass the argument to cygpath.
            arg=$( cygpath --path --ignore --mixed "$arg" )
            # Now we add the argument to the list of arguments.
            # shellcheck disable=SC2086
            set -- "$@" "$arg"
        fi
    done
    # Now we have the arguments, we need to split them by spaces to get the individual
    # arguments, because we used set -- "$@" above which puts them all into one string.
    # We need to split them back into individual arguments.
    # We use set -- to reset the argument list, and then we iterate over the arguments
    # and split them by spaces.
    set -- $(
        # We use IFS to split the arguments by spaces.
        IFS=' '
        for arg in "$@"; do
            printf '%s\n' "$arg"
        done
    )
fi

# Escape application args
save () {
    for i do printf %s\\n "$i" | sed "s/'/'\\\\''/g;1s/^/'/;\$s/\$/' \\\\/" ; done
    echo " "
}
APP_ARGS=$(save "$@")

# Collect all arguments for the java command, following the shell quoting and substitution rules
eval set -- $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS "\"-Dorg.gradle.appname=$APP_BASE_NAME\"" -classpath "\"$CLASSPATH\"" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"

# by default we should be in the correct project dir, but when run from Finder on Mac, the cwd is wrong
if [ "$(uname)" = "Darwin" ] && [ "$HOME" = "$PWD" ]; then
  cd "$(dirname "$0")"
fi

exec "$JAVACMD" "$@"
